version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
  - source: images/github3.jpg
    destination: /var/www/html
hooks:
  AfterInstall:
  - location: ./scripts/script1.sh
    timeout: 300
    runas: root
